/*Crea un programa que pregunte al usuario un número. Usando el archivo de arreglo de Pokémons, 
mostrar solo los nombres de los Pokémons cuyos números que son múltiplos de 5 desde 1 hasta el número introducido por el usuario. 
https://pastebin.com/Zzk8g7Z6.*/

// Array

const pokemons = [ 
 {Number: 1, pokemon: "bulbasaur"},
 {Number: 2, pokemon: "ivysaur"},
 {Number: 3, pokemon: "'venusaur"},
 {Number: 4, pokemon: "charmander"},
 {Number: 5, pokemon: "charmeleon"},
 {Number: 6, pokemon: "charizard"},
 {Number: 7, pokemon: "squirtle"},
 {Number: 8, pokemon: "wartortle"},
 {Number: 9, pokemon: "blastoise"},
 {Number: 10, pokemon: "caterpie"},
 {Number: 11, pokemon: "metapod"},
 {Number: 12, pokemon: "butterfree"},
 {Number: 13, pokemon: "weedle"},
 {Number: 14, pokemon: "kakuna"},
 {Number: 15, pokemon: "beedrill"},
 {Number: 16, pokemon: "pidgey"},
 {Number: 17, pokemon: "pidgeotto"},
 {Number: 18, pokemon: "pidgeot"},
 {Number: 19, pokemon: "rattata"},
 {Number: 20, pokemon: "raticate"},
 {Number: 21, pokemon: "spearow"},
 {Number: 22, pokemon: "fearow"},
 {Number: 23, pokemon: "ekans"},
 {Number: 24, pokemon: "arbok"},
 {Number: 25, pokemon: "pikachu"},
 {Number: 26, pokemon: "raichu"},
 {Number: 27, pokemon: "sandshrew"},
 {Number: 28, pokemon: "sandslash"},
 {Number: 29, pokemon: "nidoran-f"},
 {Number: 30, pokemon: "nidorina"},
 {Number: 31, pokemon: "nidoqueen"},
 {Number: 32, pokemon: "nidoran-m"},
 {Number: 33, pokemon: "nidorino"},
 {Number: 34, pokemon: "nidoking"},
 {Number: 35, pokemon: "clefairy"},
 {Number: 36, pokemon: "clefable"},
 {Number: 37, pokemon: "vulpix"},
 {Number: 38, pokemon: "ninetales"},
 {Number: 39, pokemon: "jigglypuff"},
 {Number: 40, pokemon: "wigglytuff"},
 {Number: 41, pokemon: "zubat"},
 {Number: 42, pokemon: "golbat"},
 {Number: 43, pokemon: "oddish"},
 {Number: 44, pokemon: "gloom"},
 {Number: 45, pokemon: "vileplume"},
 {Number: 46, pokemon: "paras"},
 {Number: 47, pokemon: "parasect"},
 {Number: 48, pokemon: "venonat"},
 {Number: 49, pokemon: "venomoth"},
 {Number: 50, pokemon: "diglett"},
 {Number: 51, pokemon: "dugtrio"},
 {Number: 52, pokemon: "meowth"},
 {Number: 53, pokemon: "persian"},
 {Number: 54, pokemon: "psyduck"},
 {Number: 55, pokemon: "golduck"},
 {Number: 56, pokemon: "mankey"},
 {Number: 57, pokemon: "primeape"},
 {Number: 58, pokemon: "growlithe"},
 {Number: 59, pokemon: "arcaine"},
 {Number: 60, pokemon: "poliwag"},
 {Number: 61, pokemon: "poliwrath"},
 {Number: 62, pokemon: "abra"},
 {Number: 63, pokemon: "kadabra"},
 {Number: 64, pokemon: "alakazam"},
 {Number: 65, pokemon: "machop"},
 {Number: 66, pokemon: "machoke"},
 {Number: 67, pokemon: "machamp"},
 {Number: 68, pokemon: "bellsprout"},
 {Number: 69, pokemon: "weepinbell"},
 {Number: 70, pokemon: "victreebel"},
 {Number: 71, pokemon: "tentacool"},
 {Number: 72, pokemon: "tentacruel"},
 {Number: 73, pokemon: "geodude"},
 {Number: 74, pokemon: "graveler"},
 {Number: 75, pokemon: "golem"},
 {Number: 76, pokemon: "ponyta"},
 {Number: 77, pokemon: "rapidash"},
 {Number: 78, pokemon: "slowpoke"},
 {Number: 79, pokemon: "slowbro"},
 {Number: 80, pokemon: "magnemite"},
 {Number: 81, pokemon: "magneton"},
 {Number: 82, pokemon: "far-fetchd"},
 {Number: 83, pokemon: "doduo"},
 {Number: 84, pokemon: "dodrio"},
 {Number: 85, pokemon: "seel"},
 {Number: 86, pokemon: "dewgong"},
 {Number: 87, pokemon: "grimer"},
 {Number: 88, pokemon: "muk"},
 {Number: 89, pokemon: "shellder"},
 {Number: 90, pokemon: "cloyster"},
 {Number: 91, pokemon: "gastly"},
 {Number: 92, pokemon: "haunter"},
 {Number: 93, pokemon: "gengar"},
 {Number: 94, pokemon: "onix"},
 {Number: 95, pokemon: "drowzee"},
 {Number: 96, pokemon: "hypno"},
 {Number: 97, pokemon: "krabby"},
 {Number: 98, pokemon: "kingler"},
 {Number: 99, pokemon: "voltorb"},
 {Number: 100, pokemon: "voltri"},
 
]

  let número = parseInt(prompt("Ingresa un número que sea múltiplo de 5"));

for (let contador = 1; contador <= número; contador++) {
    if (contador % 5===0 && contador <= pokemons.length) {
        const pokemonName =pokemons[contador - 1].pokemon;
    console.log(`El número ${contador}: ${pokemonName}`); 
    }  

} 

